// Tek yerden marka rengi yönetimi
// Bu değeri değiştirerek tüm uygulamanın ana rengi değişir.
export const BRAND_COLOR = '#f06543';
// İkincil/vurgu rengi (gerektiğinde dikkat çekmek için)
export const ACCENT_COLOR = '#F09D51';

export type Palette = {
	background: string;
	surface: string;
	text: string;
	textMuted: string;
	primary: string;
	primaryTextOnPrimary: string;
	accent: string;
	border: string;
	inputBg: string;
	inputPlaceholder: string;
	inputBorder: string;
	inputBorderFocus: string;
};

export const lightPalette: Palette = {
	background: '#e8e9eb',          // Light background
	surface: '#e0dfd5',             // Kart/surface
	text: '#313638',                // Yazılar
	textMuted: '#5b6166',
	primary: BRAND_COLOR,           // Ana renk
	primaryTextOnPrimary: '#ffffff',
	accent: ACCENT_COLOR,           // Vurgu
	border: '#cacccf',
	inputBg: '#ffffff',
	inputPlaceholder: '#7a8085',
	inputBorder: '#caced1',
	inputBorderFocus: BRAND_COLOR,
};

export const darkPalette: Palette = {
	background: '#313638',          // Dark background
	surface: '#424A4C',             // Kart/surface
	text: '#e8e9eb',                // Yazılar
	textMuted: '#c9cdcf',
	primary: BRAND_COLOR,           // Ana renk
	primaryTextOnPrimary: '#ffffff',
	accent: ACCENT_COLOR,           // Vurgu
	border: '#2a2f31',
	inputBg: '#2a2f31',
	inputPlaceholder: '#a1a5a7',
	inputBorder: '#4a5254',
	inputBorderFocus: BRAND_COLOR,
};

// Çoklu renk paleti desteği
export type NamedPalette = {
  id: string;
  name: string;
  light: Palette;
  dark: Palette;
};

// Varsayılan palet + 10 ek palet
export const PALETTES: NamedPalette[] = [
  {
    id: 'default',
    name: 'Default',
    light: lightPalette,
    dark: darkPalette,
  },
  {
    id: 'white',
    name: 'White',
    light: {
      background: '#ffffff',
      surface: '#f5f5f7',
      text: '#111111',
      textMuted: '#6b7280',
      primary: BRAND_COLOR,
      primaryTextOnPrimary: '#ffffff',
      accent: ACCENT_COLOR,
      border: '#e5e7eb',
      inputBg: '#ffffff',
      inputPlaceholder: '#9ca3af',
      inputBorder: '#e5e7eb',
      inputBorderFocus: BRAND_COLOR,
    },
    dark: {
      background: '#0f1115',
      surface: '#171a1f',
      text: '#f5f6f7',
      textMuted: '#b0b5bb',
      primary: BRAND_COLOR,
      primaryTextOnPrimary: '#ffffff',
      accent: ACCENT_COLOR,
      border: '#2a2f36',
      inputBg: '#121419',
      inputPlaceholder: '#9aa0a6',
      inputBorder: '#2a2f36',
      inputBorderFocus: BRAND_COLOR,
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    light: {
      background: '#e7f0f7',
      surface: '#ddecf5',
      text: '#243b53',
      textMuted: '#4a6b8a',
      primary: '#1f7ac4',
      primaryTextOnPrimary: '#ffffff',
      accent: '#29b6f6',
      border: '#c4d9ea',
      inputBg: '#ffffff',
      inputPlaceholder: '#6b8aa6',
      inputBorder: '#c4d9ea',
      inputBorderFocus: '#1f7ac4',
    },
    dark: {
      background: '#15202b',
      surface: '#1b2632',
      text: '#e6f0f8',
      textMuted: '#a9c1d6',
      primary: '#29b6f6',
      primaryTextOnPrimary: '#0b1117',
      accent: '#1f7ac4',
      border: '#0f1720',
      inputBg: '#0f1720',
      inputPlaceholder: '#8aa6bf',
      inputBorder: '#223042',
      inputBorderFocus: '#29b6f6',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    light: {
      background: '#e9f3ee',
      surface: '#dfefe7',
      text: '#1f2d27',
      textMuted: '#45695a',
      primary: '#2f855a',
      primaryTextOnPrimary: '#ffffff',
      accent: '#48bb78',
      border: '#c6e2d3',
      inputBg: '#ffffff',
      inputPlaceholder: '#6a8c7c',
      inputBorder: '#c6e2d3',
      inputBorderFocus: '#2f855a',
    },
    dark: {
      background: '#16231e',
      surface: '#1d2e26',
      text: '#e6f4ef',
      textMuted: '#b4cdc2',
      primary: '#48bb78',
      primaryTextOnPrimary: '#0c1712',
      accent: '#2f855a',
      border: '#0f1a16',
      inputBg: '#0f1a16',
      inputPlaceholder: '#9cb8ad',
      inputBorder: '#254237',
      inputBorderFocus: '#48bb78',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    light: {
      background: '#fff2e8',
      surface: '#ffe8d9',
      text: '#4a2c2a',
      textMuted: '#8b5d57',
      primary: '#f06543',
      primaryTextOnPrimary: '#ffffff',
      accent: '#f59e0b',
      border: '#ffd2b8',
      inputBg: '#ffffff',
      inputPlaceholder: '#a87a74',
      inputBorder: '#ffd2b8',
      inputBorderFocus: '#f06543',
    },
    dark: {
      background: '#2a1f1d',
      surface: '#362723',
      text: '#ffece4',
      textMuted: '#e0b4a8',
      primary: '#f59e0b',
      primaryTextOnPrimary: '#241a17',
      accent: '#f06543',
      border: '#1e1614',
      inputBg: '#1e1614',
      inputPlaceholder: '#d9b3a9',
      inputBorder: '#4a312c',
      inputBorderFocus: '#f59e0b',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    light: {
      background: '#f3f0ff',
      surface: '#ece7ff',
      text: '#2a2440',
      textMuted: '#5a5380',
      primary: '#6d5bd0',
      primaryTextOnPrimary: '#ffffff',
      accent: '#b794f4',
      border: '#d8cffc',
      inputBg: '#ffffff',
      inputPlaceholder: '#7b73a6',
      inputBorder: '#d8cffc',
      inputBorderFocus: '#6d5bd0',
    },
    dark: {
      background: '#1d1930',
      surface: '#261f3f',
      text: '#efeaff',
      textMuted: '#cdbef8',
      primary: '#b794f4',
      primaryTextOnPrimary: '#161226',
      accent: '#6d5bd0',
      border: '#141126',
      inputBg: '#141126',
      inputPlaceholder: '#b4a6ea',
      inputBorder: '#302857',
      inputBorderFocus: '#b794f4',
    },
  },
  {
    id: 'coral',
    name: 'Coral',
    light: {
      background: '#fff1f0',
      surface: '#ffe4e2',
      text: '#402426',
      textMuted: '#7a4a4d',
      primary: '#ff6b6b',
      primaryTextOnPrimary: '#ffffff',
      accent: '#ffa07a',
      border: '#ffcfcf',
      inputBg: '#ffffff',
      inputPlaceholder: '#996e71',
      inputBorder: '#ffcfcf',
      inputBorderFocus: '#ff6b6b',
    },
    dark: {
      background: '#2a1b1d',
      surface: '#3a2427',
      text: '#ffecee',
      textMuted: '#f5b6bd',
      primary: '#ffa07a',
      primaryTextOnPrimary: '#1c1213',
      accent: '#ff6b6b',
      border: '#1b1213',
      inputBg: '#1b1213',
      inputPlaceholder: '#e9b2b8',
      inputBorder: '#4a2d31',
      inputBorderFocus: '#ffa07a',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald',
    light: {
      background: '#ebfff5',
      surface: '#dcfbef',
      text: '#12382b',
      textMuted: '#2c6d57',
      primary: '#10b981',
      primaryTextOnPrimary: '#ffffff',
      accent: '#34d399',
      border: '#c7f7e6',
      inputBg: '#ffffff',
      inputPlaceholder: '#4f8f79',
      inputBorder: '#c7f7e6',
      inputBorderFocus: '#10b981',
    },
    dark: {
      background: '#0b1e18',
      surface: '#0f2a21',
      text: '#e6fff6',
      textMuted: '#b4eedd',
      primary: '#34d399',
      primaryTextOnPrimary: '#07120e',
      accent: '#10b981',
      border: '#081511',
      inputBg: '#081511',
      inputPlaceholder: '#9ae6c7',
      inputBorder: '#163f33',
      inputBorderFocus: '#34d399',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    light: {
      background: '#fff9ec',
      surface: '#fff3d6',
      text: '#3d2f12',
      textMuted: '#6a5a2e',
      primary: '#f59e0b',
      primaryTextOnPrimary: '#1a1406',
      accent: '#fbbf24',
      border: '#ffe5a8',
      inputBg: '#ffffff',
      inputPlaceholder: '#8b783f',
      inputBorder: '#ffe5a8',
      inputBorderFocus: '#f59e0b',
    },
    dark: {
      background: '#211a0b',
      surface: '#2b210d',
      text: '#fff6e3',
      textMuted: '#f3deac',
      primary: '#fbbf24',
      primaryTextOnPrimary: '#1a1406',
      accent: '#f59e0b',
      border: '#161107',
      inputBg: '#161107',
      inputPlaceholder: '#e8d39a',
      inputBorder: '#3a2e12',
      inputBorderFocus: '#fbbf24',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    light: {
      background: '#fff1f5',
      surface: '#ffe4ed',
      text: '#401927',
      textMuted: '#7a3a52',
      primary: '#e11d48',
      primaryTextOnPrimary: '#ffffff',
      accent: '#fb7185',
      border: '#ffc2d1',
      inputBg: '#ffffff',
      inputPlaceholder: '#8f5066',
      inputBorder: '#ffc2d1',
      inputBorderFocus: '#e11d48',
    },
    dark: {
      background: '#2a0f18',
      surface: '#3a1621',
      text: '#ffe9ef',
      textMuted: '#f5b2c1',
      primary: '#fb7185',
      primaryTextOnPrimary: '#1a0a0f',
      accent: '#e11d48',
      border: '#1a080e',
      inputBg: '#1a080e',
      inputPlaceholder: '#e7a8b8',
      inputBorder: '#4a1d29',
      inputBorderFocus: '#fb7185',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    light: {
      background: '#eef2f6',
      surface: '#e3e9ef',
      text: '#1f2937',
      textMuted: '#6b7280',
      primary: '#475569',
      primaryTextOnPrimary: '#ffffff',
      accent: '#64748b',
      border: '#cfd8e3',
      inputBg: '#ffffff',
      inputPlaceholder: '#7b8696',
      inputBorder: '#cfd8e3',
      inputBorderFocus: '#475569',
    },
    dark: {
      background: '#0f172a',
      surface: '#111827',
      text: '#e5e7eb',
      textMuted: '#c7cbd1',
      primary: '#94a3b8',
      primaryTextOnPrimary: '#0b0f19',
      accent: '#475569',
      border: '#0b1220',
      inputBg: '#0b1220',
      inputPlaceholder: '#aab3c2',
      inputBorder: '#1f2937',
      inputBorderFocus: '#94a3b8',
    },
  },
  {
    id: 'indigo',
    name: 'Indigo',
    light: {
      background: '#eef2ff',
      surface: '#e0e7ff',
      text: '#1e1b4b',
      textMuted: '#4c4a7d',
      primary: '#4f46e5',
      primaryTextOnPrimary: '#ffffff',
      accent: '#818cf8',
      border: '#c7d2fe',
      inputBg: '#ffffff',
      inputPlaceholder: '#6b67a6',
      inputBorder: '#c7d2fe',
      inputBorderFocus: '#4f46e5',
    },
    dark: {
      background: '#111233',
      surface: '#17174a',
      text: '#eef1ff',
      textMuted: '#c9cdfb',
      primary: '#818cf8',
      primaryTextOnPrimary: '#0b0c21',
      accent: '#4f46e5',
      border: '#0b0c21',
      inputBg: '#0b0c21',
      inputPlaceholder: '#b8bdf7',
      inputBorder: '#23245a',
      inputBorderFocus: '#818cf8',
    },
  },
  {
    id: 'teal',
    name: 'Teal',
    light: {
      background: '#e6fffb',
      surface: '#d9f7f5',
      text: '#123b38',
      textMuted: '#2a6d69',
      primary: '#14b8a6',
      primaryTextOnPrimary: '#ffffff',
      accent: '#2dd4bf',
      border: '#bfeeed',
      inputBg: '#ffffff',
      inputPlaceholder: '#4f8f8b',
      inputBorder: '#bfeeed',
      inputBorderFocus: '#14b8a6',
    },
    dark: {
      background: '#0b1f1e',
      surface: '#0f2a29',
      text: '#e6fffb',
      textMuted: '#b2ece7',
      primary: '#2dd4bf',
      primaryTextOnPrimary: '#071211',
      accent: '#14b8a6',
      border: '#071211',
      inputBg: '#071211',
      inputPlaceholder: '#9ce5df',
      inputBorder: '#163f3d',
      inputBorderFocus: '#2dd4bf',
    },
  },
];

